CLASS zcl_bp_vendor_root DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zvendor_root.
PUBLIC SECTION.
    CLASS-DATA gt_log TYPE STANDARD TABLE OF zvendor01_log.
ENDCLASS.

CLASS zcl_bp_vendor_root IMPLEMENTATION.
ENDCLASS.
